[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Mathias Staricka <mstaricka@gmail.com>"]
edition = "2018"
readme = "README.txt"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
